trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: databricks_secrets

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install databricks-cli
    mkdir -p ~/.databricks
    printf "[DEFAULT]\nhost = %s\ntoken = %s\n" "$DATABRICKS_HOST" "$DATABRICKS_TOKEN" > ~/.databricks/config
    cat ~/.databricks/config  # Just for verification (optional, remove later)
    databricks workspace import ./RentalPipeline/rental_pipeline.py /Users/banu@virtualbuddy.in/RentalPipeline/rental_pipeline.py --language PYTHON --overwrite
  displayName: 'Deploy notebook to Databricks'
